pipelines:
  Payroll:
    group: apis
    materials:
      repo:
        git: https://github.com/exarcol/payroll.git
        branch: master
    stages:
      - Unit_Tests:
          jobs:
            run_tests:
              tasks:
                - exec:
                    command: mvn
                    arguments:
                      - clean
                      - test
      - Create_Uberjar:
          jobs:
            compile_to_Ubejar:
              artifacts:
                - build:
                    source: '**/payroll-1.0.war'
                    destination: target/
                - build:
                    source: '**/payroll-1.0-swarm.jar'
                    destination: target/
              tasks:
                - exec:
                    command: mvn
                    arguments:
                      - '-Dmaven.test.skip=true'
                      - clean
                      - package
                      - wildfly-swarm:package
      - Upload_to_loc:
          jobs:
            upload_to_loc:
              tasks:
                - fetch:
                    stage: Create_Uberjar
                    job: compile_to_Ubejar
                    source: target/target/payroll-1.0-swarm.jar
                    destination: app/
                    is_file: true
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - /godata/pr_copy_local.sh  
      - Deploy_on_loc:
          jobs:
            deploy_on_loc:
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - /godata/pr_stop_server_local.sh
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - /godata/pr_deploy_local.sh
